#Step 1

In [4]:
import os
import pandas as pd

df = pd.read_csv("bbc-news-data.csv",sep="\t")

df = df.head(30)

df

,category,filename,title,content
0,business,001.txt,Ad sales boost Time Warner profit,Quarterly profits at US media giant TimeWarne...
1,business,002.txt,Dollar gains on Greenspan speech,The dollar has hit its highest level against ...
2,business,003.txt,Yukos unit buyer faces loan claim,The owners of embattled Russian oil giant Yuk...
3,business,004.txt,High fuel prices hit BA's profits,British Airways has blamed high fuel prices f...
4,business,005.txt,Pernod takeover talk lifts Domecq,Shares in UK drinks and food firm Allied Dome...
5,business,006.txt,Japan narrowly escapes recession,Japan's economy teetered on the brink of a te...
6,business,007.txt,Jobs growth still slow in the US,The US created fewer jobs than expected in Ja...
7,business,008.txt,India calls for fair trade rules,"India, which attends the G7 meeting of seven ..."
8,business,009.txt,Ethiopia's crop production up 24%,Ethiopia produced 14.27 million tonnes of cro...
9,business,010.txt,Court rejects $280bn tobacco case,A US government claim accusing the country's ...
10,business,011.txt,Ask Jeeves tips online ad revival,Ask Jeeves has become the third leading onlin...
11,business,012.txt,Indonesians face fuel price rise,Indonesia's government has confirmed it is co...
12,business,013.txt,Peugeot deal boosts Mitsubishi,Struggling Japanese car maker Mitsubishi Moto...
13,business,014.txt,Telegraph newspapers axe 90 jobs,The Daily and Sunday Telegraph newspapers are...
14,business,015.txt,Air passengers win new EU rights,Air passengers who are unable to board their ...
15,business,016.txt,China keeps tight rein on credit,China's efforts to stop the economy from over...
16,business,017.txt,Parmalat boasts doubled profits,"Parmalat, the Italian food group at the centr..."
17,business,018.txt,India's rupee hits five-year high,India's rupee has hit a five-year high after ...
18,business,019.txt,India widens access to telecoms,India has raised the limit for foreign direct...
19,business,020.txt,Call centre users 'lose patience',Customers trying to get through to call centr...
20,business,021.txt,Rank 'set to sell off film unit',Leisure group Rank could unveil plans to deme...
21,business,022.txt,Sluggish economy hits German jobs,The number of people out of work in Europe's ...
22,business,023.txt,Mixed signals from French economy,The French economy picked up speed at the end...
23,business,024.txt,US trade gap hits record in 2004,The gap between US exports and imports hit an...
24,business,025.txt,Yukos loses US bankruptcy battle,A judge has dismissed an attempt by Russian o...
25,business,026.txt,Safety alert as GM recalls cars,The world's biggest carmaker General Motors (...
26,business,027.txt,"Steel firm 'to cut' 45,000 jobs","Mittal Steel, one of the world's largest stee..."
27,business,028.txt,Strong demand triggers oil rally,Crude oil prices surged back above the $47 a ...
28,business,029.txt,UK firm faces Venezuelan land row,Venezuelan authorities have said they will se...
29,business,030.txt,Soaring oil 'hits world economy',The soaring cost of oil has hit global econom...

In [5]:
print("Number of articles:", len(df))
print("Columns:", df.columns.tolist())

Number of articles: 30
Columns: ['category', 'filename', 'title', 'content']

#Step 2

In [9]:
from langchain.chat_models import init_chat_model
from langchain_core.prompts import PromptTemplate

model_name = "openai/gpt-oss-120b"

llm = init_chat_model(
    model_name,
    model_provider="groq"
)

topic_prompt = PromptTemplate(
    input_variables=["article"],
    template="""
You are a news topic classification system.

Classify the following BBC news article into exactly ONE
of these five categories:

Business
Entertainment
Politics
Sport
Tech

Examples:

Article:
"Shares in several major companies rose after investors
responded positively to the latest economic figures."

Category:
Business


Article:
"The football team secured a dramatic victory after
scoring in the final minutes of the match."

Category:
Sport


Article:
"The government announced new legislation following
a debate in parliament."

Category:
Politics


Article:
"A technology company launched a new smartphone with
an improved processor and longer battery life."

Category:
Tech


Article:
"The latest Hollywood film received widespread praise
from audiences and critics."

Category:
Entertainment


Now classify the following article.

Article:
{article}

Return ONLY the category name.
Do not provide an explanation.
"""
)

In [10]:
topic_chain = topic_prompt | llm

In [11]:
sample_article = df.iloc[0]["content"]

topic_result = topic_chain.invoke({
    "article": sample_article
})

print("Article:")
print(sample_article[:1000])

print("\n predicted Topic:")
print(topic_result.content)

Article:
 Quarterly profits at US media giant TimeWarner jumped 76% to $1.13bn (£600m) for the three months to December, from $639m year-earlier.  The firm, which is now one of the biggest investors in Google, benefited from sales of high-speed internet connections and higher advert sales. TimeWarner said fourth quarter sales rose 2% to $11.1bn from $10.9bn. Its profits were buoyed by one-off gains which offset a profit dip at Warner Bros, and less users for AOL.  Time Warner said on Friday that it now owns 8% of search-engine Google. But its own internet business, AOL, had has mixed fortunes. It lost 464,000 subscribers in the fourth quarter profits were lower than in the preceding three quarters. However, the company said AOL's underlying profit before exceptional items rose 8% on the back of stronger internet advertising revenues. It hopes to increase subscribers by offering the online service free to TimeWarner internet customers and will try to sign up AOL's existing customers for high-spe

 predicted Topic:
Business

#Step 3

In [12]:
summary_prompt = PromptTemplate(
    input_variables=["article"],
    template="""
You are a professional news summarization system.

Summarize the following BBC news article in 2-3 sentences.

Requirements:
1. Capture the main points and key information.
2. Include who, what, when, where, and why when applicable.
3. Keep the summary concise and factual.
4. Do not add personal opinions or commentary.
5. Do not introduce information that is not present in the article.

Article:
{article}

Summary:
"""
)

summary_chain = summary_prompt | llm

In [13]:
summary_result = summary_chain.invoke({
    "article": sample_article
})

print("Original Article:")
print(sample_article[:1000])

print("\nSummary:")
print(summary_result.content)

Original Article:
 Quarterly profits at US media giant TimeWarner jumped 76% to $1.13bn (£600m) for the three months to December, from $639m year-earlier.  The firm, which is now one of the biggest investors in Google, benefited from sales of high-speed internet connections and higher advert sales. TimeWarner said fourth quarter sales rose 2% to $11.1bn from $10.9bn. Its profits were buoyed by one-off gains which offset a profit dip at Warner Bros, and less users for AOL.  Time Warner said on Friday that it now owns 8% of search-engine Google. But its own internet business, AOL, had has mixed fortunes. It lost 464,000 subscribers in the fourth quarter profits were lower than in the preceding three quarters. However, the company said AOL's underlying profit before exceptional items rose 8% on the back of stronger internet advertising revenues. It hopes to increase subscribers by offering the online service free to TimeWarner internet customers and will try to sign up AOL's existing customers for high-spe

Summary:
Time Warner reported fourth‑quarter profit of $1.13 billion—a 76 % rise—for the three months to December, with sales up 2 % to $11.1 billion, boosted by high‑speed internet connections, higher advertising revenue and one‑off gains that offset a dip at Warner Bros and losses at AOL. The company, now holding an 8 % stake in Google, said AOL lost 464,000 subscribers but its underlying profit rose 8 % on stronger ad sales, while its film division’s profit fell 27 % after box‑office flops; full‑year profit increased 27 % to $3.36 billion as revenue grew 6.4 % to $42.09 billion. Time Warner will restate its 2000 and 2003 accounts following an SEC probe into AOL and has offered to pay $300 million to settle related charges.

#Step4

In [14]:
entity_prompt = PromptTemplate(
    input_variables=["article"],
    template="""
You are an information extraction system.

Extract the important entities mentioned in the following
BBC news article.

Identify entities in these three categories:

1. People
2. Organizations
3. Locations

Rules:
- Only include entities that are actually mentioned in the article.
- Do not invent entities.
- If no entity exists for a category, return an empty list.
- Return ONLY valid JSON.
- Do not include markdown or explanations.

Required JSON format:

{{
    "People": [],
    "Organizations": [],
    "Locations": []
}}

Article:
{article}
"""
)

entity_chain = entity_prompt | llm

In [15]:
entity_result = entity_chain.invoke({
    "article": sample_article
})

print("Extracted Entities:")
print(entity_result.content)

Extracted Entities:
{
    "People": ["Richard Parsons"],
    "Organizations": ["TimeWarner", "Google", "Warner Bros", "AOL", "US Securities Exchange Commission", "SEC", "Bertelsmann", "AOL Europe"],
    "Locations": ["US"]
}

#Step5

In [17]:
import time

detected_topics = []
summaries = []
key_entities = []

BATCH_SIZE = 5
BATCH_DELAY = 10

for batch_start in range(0, len(df), BATCH_SIZE):

    batch_end = min(batch_start + BATCH_SIZE, len(df))

    batch = df.iloc[batch_start:batch_end]

    print(
        f"\nProcessing articles "
        f"{batch_start + 1}-{batch_end} of {len(df)}..."
    )

    for index, row in batch.iterrows():

        article = row["content"]

        print(f"  Processing article {index + 1}...")

        # ----------------------------------------
        # Topic Classification
        # ----------------------------------------

        topic_result = topic_chain.invoke({
            "article": article
        })

        detected_topic = topic_result.content.strip()

        # ----------------------------------------
        # Summarization
        # ----------------------------------------

        summary_result = summary_chain.invoke({
            "article": article
        })

        summary = summary_result.content.strip()

        # ----------------------------------------
        # Entity Extraction
        # ----------------------------------------

        entity_result = entity_chain.invoke({
            "article": article
        })

        entities = entity_result.content.strip()

        # ----------------------------------------
        # Store results
        # ----------------------------------------

        detected_topics.append(detected_topic)
        summaries.append(summary)
        key_entities.append(entities)

    print(f"Batch {batch_start // BATCH_SIZE + 1} completed.")

    # Wait before starting next batch
    if batch_end < len(df):
        print(f"Waiting {BATCH_DELAY} seconds before next batch...")
        time.sleep(BATCH_DELAY)


print("\nProcessing completed!")

Processing articles 1-5 of 30...
  Processing article 1...
  Processing article 2...
  Processing article 3...
  Processing article 4...
  Processing article 5...
Batch 1 completed.
Waiting 10 seconds before next batch...

Processing articles 6-10 of 30...
  Processing article 6...
  Processing article 7...
  Processing article 8...
  Processing article 9...
  Processing article 10...
Batch 2 completed.
Waiting 10 seconds before next batch...

Processing articles 11-15 of 30...
  Processing article 11...
  Processing article 12...
  Processing article 13...
  Processing article 14...
  Processing article 15...
Batch 3 completed.
Waiting 10 seconds before next batch...

Processing articles 16-20 of 30...
  Processing article 16...
  Processing article 17...
  Processing article 18...
  Processing article 19...
  Processing article 20...
Batch 4 completed.
Waiting 10 seconds before next batch...

Processing articles 21-25 of 30...
  Processing article 21...
  Processing article 22...
  Processing article 23...
  Processing article 24...
  Processing article 25...
Batch 5 completed.
Waiting 10 seconds before next batch...

Processing articles 26-30 of 30...
  Processing article 26...
  Processing article 27...
  Processing article 28...
  Processing article 29...
  Processing article 30...
Batch 6 completed.

Processing completed!

In [18]:
df["Detected_Topic"] = detected_topics
df["Summary"] = summaries
df["Key_Entities"] = key_entities

df

,category,filename,title,content,Detected_Topic,Summary,Key_Entities
0,business,001.txt,Ad sales boost Time Warner profit,Quarterly profits at US media giant TimeWarne...,Business,TimeWarner reported a 76 % jump in fourth‑quar...,"{\n ""People"": [""Richard Parsons""],\n ""Or..."
1,business,002.txt,Dollar gains on Greenspan speech,The dollar has hit its highest level against ...,Business,The dollar rose to $1.2871 per euro in late‑da...,"{\n ""People"": [""Alan Greenspan"", ""Robert Si..."
2,business,003.txt,Yukos unit buyer faces loan claim,The owners of embattled Russian oil giant Yuk...,Business,"The owners of Russia’s former oil giant Yukos,...","{\n ""People"": [\n ""Jamie Firestone"",..."
3,business,004.txt,High fuel prices hit BA's profits,British Airways has blamed high fuel prices f...,Business,British Airways reported that pre‑tax profit f...,"{\n ""People"": [""Rod Eddington"", ""Mike Powel..."
4,business,005.txt,Pernod takeover talk lifts Domecq,Shares in UK drinks and food firm Allied Dome...,Business,Shares in UK drinks and food group Allied Dome...,"{\n ""People"": [],\n ""Organizations"": [\n..."
5,business,006.txt,Japan narrowly escapes recession,Japan's economy teetered on the brink of a te...,Business,Japan’s economy barely grew by 0.1% in the thr...,"{\n ""People"": [""Heizo Takenaka"", ""Paul Shea..."
6,business,007.txt,Jobs growth still slow in the US,The US created fewer jobs than expected in Ja...,Business,"In January, the U.S. Labor Department reported...","{\n ""People"": [""President Bush"", ""Herbert H..."
7,business,008.txt,India calls for fair trade rules,"India, which attends the G7 meeting of seven ...",Business,India’s finance minister Palaniappan Chidambar...,"{\n ""People"": [\n ""Palaniappan Chida..."
8,business,009.txt,Ethiopia's crop production up 24%,Ethiopia produced 14.27 million tonnes of cro...,Business,Ethiopia’s crop output rose to 14.27 million t...,"{\n ""People"": [""Henri Josserand""],\n ""Or..."
9,business,010.txt,Court rejects $280bn tobacco case,A US government claim accusing the country's ...,Business,A U.S. Court of Appeals for the District of Co...,"{\n ""People"": [],\n ""Organizations"": [\n..."
10,business,011.txt,Ask Jeeves tips online ad revival,Ask Jeeves has become the third leading onlin...,Business,Ask Jeeves reported that its fourth‑quarter 20...,"{\n ""People"": [],\n ""Organizations"": [""A..."
11,business,012.txt,Indonesians face fuel price rise,Indonesia's government has confirmed it is co...,Politics,Indonesia’s government is weighing a fuel‑pric...,"{\n ""People"": [""Susilo Bambang Yudhoyono"", ..."
12,business,013.txt,Peugeot deal boosts Mitsubishi,Struggling Japanese car maker Mitsubishi Moto...,Business,Mitsubishi Motors announced a memorandum of un...,"{\n ""People"": [""Takashi Nishioka""],\n ""O..."
13,business,014.txt,Telegraph newspapers axe 90 jobs,The Daily and Sunday Telegraph newspapers are...,Business,The Daily and Sunday Telegraph announced on Fr...,"{\n ""People"": [\n ""Jeremy Dear"",\n ..."
14,business,015.txt,Air passengers win new EU rights,Air passengers who are unable to board their ...,Politics,"The European Commission introduced new rules, ...","{\n ""People"": [\n ""Michael Cawley"",\..."
15,business,016.txt,China keeps tight rein on credit,China's efforts to stop the economy from over...,Business,State media reported that China will maintain ...,"{\n ""People"": [],\n ""Organizations"": [""s..."
16,business,017.txt,Parmalat boasts doubled profits,"Parmalat, the Italian food group at the centr...",Business,"Parmalat, the Italian food group that filed fo...","{\n ""People"": [""Enrico Bondi""],\n ""Organ..."
17,business,018.txt,India's rupee hits five-year high,India's rupee has hit a five-year high after ...,Business,India’s rupee rose to a five‑year high of 43.3...,"{\n ""People"": [""Bhanu Baweja""],\n ""Organ..."
18,business,019.txt,India widens access to telecoms,India has raised the limit for foreign direct...,Business,India has raised the ceiling for foreign direc...,"{\n ""People"": [\n ""Dayanidhi Maran"",..."
19,business,020.txt,Call centre users 'lose patience',Customers trying to get through to call centr...,Business,A Dimension Data‑commissioned survey of 166 ca...,"{\n ""People"": [""Cara Diemont"", ""Vivaldi""],\..."
20,business,021.txt,Rank 'set to sell off film unit',Leisure group Rank could unveil plans to deme...,Business,Leisure group Rank is expected to announce at ...,"{\n ""People"": [""Mike Smith""],\n ""Organiz..."
21,business,022.txt,Sluggish economy hits German jobs,The number of people out of work in Europe's ...,Business,"In November, German unemployment rose by 7,000...","{\n ""People"": [""Frank-Juergen Weise"", ""Gerh..."
22,business,023.txt,Mixed signals from French economy,The French economy picked up speed at the end...,Business,France’s economy accelerated in the final quar...,"{\n ""People"": [""David Naude""],\n ""Organi..."
23,business,024.txt,US trade gap hits record in 2004,The gap between US exports and imports hit an...,Business,In 2004 the United States recorded a record tr...,"{\n ""People"": [""President Bush"", ""Marie-Pie..."
24,business,025.txt,Yukos loses US bankruptcy battle,A judge has dismissed an attempt by Russian o...,Business,A Texas judge dismissed Yukos’s attempt to obt...,"{\n ""People"": [\n ""Mikhail Khodorkov..."
25,business,026.txt,Safety alert as GM recalls cars,The world's biggest carmaker General Motors (...,Business,"General Motors is recalling about 200,000 vehi...","{\n ""People"": [],\n ""Organizations"": [\n..."
26,business,027.txt,"Steel firm 'to cut' 45,000 jobs","Mittal Steel, one of the world's largest stee...",Business,Mittal Steel’s chief executive Lakshmi Mittal ...,"{\n ""People"": [""Lakshmi Mittal""],\n ""Org..."
27,business,028.txt,Strong demand triggers oil rally,Crude oil prices surged back above the $47 a ...,Business,"On Thursday, crude oil prices climbed above $4...","{\n ""People"": [""Orin Middleton""],\n ""Org..."
28,business,029.txt,UK firm faces Venezuelan land row,Venezuelan authorities have said they will se...,Politics,Venezuelan officials in Cojedes state announce...,"{\n ""People"": [""President Chavez"", ""Alexis ..."
29,business,030.txt,Soaring oil 'hits world economy',The soaring cost of oil has hit global econom...,Business,The OECD said that soaring oil prices have for...,"{\n ""People"": [""Jean-Philippe Cotis"", ""Vinc..."

#Part2

#Step1

In [20]:
import pandas as pd
import json
import time

from langchain.chat_models import init_chat_model
from langchain_core.prompts import PromptTemplate


# Groq LLM
model_name = "openai/gpt-oss-120b"

llm = init_chat_model(
    model_name,
    model_provider="groq"
)

print("LLM initialized successfully!")

jobs_df = pd.read_csv("job_title_des.csv")
print("Original dataset shape",jobs_df.shape)

jobs_df = jobs_df.head(25).copy()

print("Dataset used for assignment:", jobs_df.shape)

display(jobs_df.head())

LLM initialized successfully!
Original dataset shape (2277, 3)
Dataset used for assignment: (25, 3)

,Unnamed: 0,Job Title,Job Description
0,0,Flutter Developer,We are looking for hire experts flutter develo...
1,1,Django Developer,PYTHON/DJANGO (Developer/Lead) - Job Code(PDJ ...
2,2,Machine Learning,"Data Scientist (Contractor)\r\n\r\nBangalore, ..."
3,3,iOS Developer,JOB DESCRIPTION:\r\n\r\nStrong framework outsi...
4,4,Full Stack Developer,job responsibility full stack engineer – react...

In [21]:
jobs_df = jobs_df.rename(columns={
    "Job Title": "Job_Title",
    "Job Description": "Job_Description"
})

In [24]:
job_analysis_prompt = PromptTemplate(
    input_variables=[
        "job_title",
        "job_description"
    ],
    template="""
You are a professional job-posting analysis system.

Analyze the following job posting.

TASK 1:
Classify the job into exactly ONE category:

Technology/IT
Finance
Marketing
Healthcare
Education
Others

TASK 2:
Extract:

1. Required Skills/Technologies
2. Education Requirement
3. Experience Requirement

RULES:

- Only extract information explicitly mentioned.
- Do not invent information.
- If education is not mentioned, return "Not specified".
- If experience is not mentioned, return "Not specified".
- Skills must be a list.
- Return ONLY valid JSON.
- Do not use markdown.
- Do not provide explanations.

Return exactly:

{{
    "Predicted_Category": "Technology/IT",
    "Required_Skills": [],
    "Education_Required": "Not specified",
    "Experience_Required": "Not specified"
}}

JOB TITLE:
{job_title}

JOB DESCRIPTION:
{job_description}
"""
)

job_analysis_chain = job_analysis_prompt | llm

In [25]:
sample_job = jobs_df.iloc[0]

sample_result = job_analysis_chain.invoke({
    "job_title": sample_job["Job_Title"],
    "job_description": sample_job["Job_Description"]
})

print("\n===== SAMPLE OUTPUT =====")
print(sample_result.content)

===== SAMPLE OUTPUT =====
{
    "Predicted_Category": "Technology/IT",
    "Required_Skills": ["Flutter"],
    "Education_Required": "Not specified",
    "Experience_Required": "1 year (Preferred)"
}

In [26]:
predicted_categories = []
required_skills = []
education_requirements = []
experience_requirements = []

BATCH_SIZE = 5
BATCH_DELAY = 10


for batch_start in range(
    0,
    len(jobs_df),
    BATCH_SIZE
):

    batch_end = min(
        batch_start + BATCH_SIZE,
        len(jobs_df)
    )

    batch = jobs_df.iloc[
        batch_start:batch_end
    ]

    print(
        f"\nProcessing jobs "
        f"{batch_start + 1}-{batch_end} "
        f"of {len(jobs_df)}..."
    )

    for index, row in batch.iterrows():

        print(
            f"  Processing job "
            f"{index + 1}..."
        )

        result = job_analysis_chain.invoke({
            "job_title": row["Job_Title"],
            "job_description": row["Job_Description"]
        })

        response = result.content.strip()

        try:

            data = json.loads(response)

            predicted_categories.append(
                data.get(
                    "Predicted_Category",
                    "Others"
                )
            )

            required_skills.append(
                data.get(
                    "Required_Skills",
                    []
                )
            )

            education_requirements.append(
                data.get(
                    "Education_Required",
                    "Not specified"
                )
            )

            experience_requirements.append(
                data.get(
                    "Experience_Required",
                    "Not specified"
                )
            )

        except json.JSONDecodeError:

            print(
                f"⚠ Could not parse JSON "
                f"for job {index + 1}"
            )

            predicted_categories.append(
                "Others"
            )

            required_skills.append([])

            education_requirements.append(
                "Not specified"
            )

            experience_requirements.append(
                "Not specified"
            )

    print(
        f"Batch "
        f"{batch_start // BATCH_SIZE + 1} "
        f"completed."
    )

    if batch_end < len(jobs_df):

        print(
            f"Waiting {BATCH_DELAY} seconds..."
        )

        time.sleep(BATCH_DELAY)

Processing jobs 1-5 of 25...
  Processing job 1...
  Processing job 2...
  Processing job 3...
  Processing job 4...
  Processing job 5...
Batch 1 completed.
Waiting 10 seconds...

Processing jobs 6-10 of 25...
  Processing job 6...
  Processing job 7...
  Processing job 8...
  Processing job 9...
  Processing job 10...
Batch 2 completed.
Waiting 10 seconds...

Processing jobs 11-15 of 25...
  Processing job 11...
  Processing job 12...
  Processing job 13...
  Processing job 14...
  Processing job 15...
Batch 3 completed.
Waiting 10 seconds...

Processing jobs 16-20 of 25...
  Processing job 16...
  Processing job 17...
  Processing job 18...
  Processing job 19...
  Processing job 20...
Batch 4 completed.
Waiting 10 seconds...

Processing jobs 21-25 of 25...
  Processing job 21...
  Processing job 22...
  Processing job 23...
  Processing job 24...
  Processing job 25...
Batch 5 completed.

In [27]:
jobs_df["Predicted_Category"] = (
    predicted_categories
)

jobs_df["Required_Skills"] = (
    required_skills
)

jobs_df["Education_Required"] = (
    education_requirements
)

jobs_df["Experience_Required"] = (
    experience_requirements
)

In [28]:
print("\n==========================================")
print("FINAL JOB ANALYSIS DATAFRAME")
print("==========================================")

display(jobs_df)


print("\n==========================================")
print("REQUIRED OUTPUT COLUMNS")
print("==========================================")

display(
    jobs_df[
        [
            "Job_Title",
            "Predicted_Category",
            "Required_Skills",
            "Education_Required",
            "Experience_Required"
        ]
    ]
)

==========================================
FINAL JOB ANALYSIS DATAFRAME
==========================================

,Unnamed: 0,Job_Title,Job_Description,Predicted_Category,Required_Skills,Education_Required,Experience_Required
0,0,Flutter Developer,We are looking for hire experts flutter develo...,Technology/IT,[Flutter],Not specified,1 year (Preferred)
1,1,Django Developer,PYTHON/DJANGO (Developer/Lead) - Job Code(PDJ ...,Technology/IT,"[Python, Django, Flask, REST, RPC, Linux, SQL,...",Not specified,Not specified
2,2,Machine Learning,"Data Scientist (Contractor)\r\n\r\nBangalore, ...",Technology/IT,"[Machine Learning, Deep Learning, Python, Java...","Graduate or M.Sc. in Computer Science, Mathema...",At least 3 years of hands-on development of co...
3,3,iOS Developer,JOB DESCRIPTION:\r\n\r\nStrong framework outsi...,Technology/IT,"[iOS development, Objective-C, Cocoa Touch, Co...",Not specified,Published one or more iOS apps in the App Store
4,4,Full Stack Developer,job responsibility full stack engineer – react...,Technology/IT,"[React, React Native, Redux, Angular, Vue, Jav...",Not specified,"5+ years web development, 2+ years recent Reac..."
5,5,Java Developer,Software Developer - Integration*\r\nImmediate...,Technology/IT,"[C#, .NET, .NET Core, HTML5, CSS3, MsSQL, MySQ...","Bachelor's Degree in Computer Science, Informa...",2 years
6,6,Full Stack Developer,senior full stack developer \- 1800026h cwt lo...,Technology/IT,"[Node.js, Java, MongoDB, Elasticsearch, Redis,...","B.Sc degree in Computer Science, Engineering, ...",Minimum 2 years of relevant experience
7,7,JavaScript Developer,"Job Description:\r\n\r\nReactJS + NodeJs, Azur...",Technology/IT,"[ReactJS, NodeJS, Azure Functions, GraphQL, HT...","Any graduation, Any PG, Any Doctorate",3-8 years
8,8,DevOps Engineer,Main Responsibilities and Deliverables:\r\nMan...,Technology/IT,"[Bash, Ruby, Python, Java, Puppet, Chef, Cloud...",Not specified,Not specified
9,9,Software Engineer,"Overview\r\n\r\n\r\nBased in Silicon Valley, T...",Technology/IT,"[REST API, C/C++ (Linux/Unix), Python, Go, Git...","BS or MS in Computer Engineering, Computer Sci...",Minimum 7 years of software development experi...
10,10,Database Administrator,richardsontexasunited state bausp4 boeing comp...,Technology/IT,"[Advanced SQL, Oracle, Database design, Databa...",Technical bachelor's degree (or higher) in a r...,Typically 9 years of related work experience
11,11,Machine Learning,"Remote, Any where\r\n2 - 4 years\r\n₹8L - ₹12L...",Technology/IT,"[TensorFlow, OpenCV, Python, Artificial Neural...",Not specified,2-4 years
12,12,Machine Learning,"Excited by Big Data, Machine Learning and Pred...",Technology/IT,"[Machine Learning, Data Mining, Predictive Mod...","Masters and/or PhD in Computer Science, Machin...",Experience in predictive modelling and analysi...
13,13,Software Engineer,As a member of our Software Engineering Group ...,Technology/IT,"[HTML5, CSS 3.0, Bootstrap, Angular 8+, JavaSc...",Not specified,5-8 years
14,14,Software Engineer,JOB DESCRIPTION\r\n\r\nJob Title: Software Eng...,Technology/IT,"[Object-oriented design, Java, .NET, Relationa...",Bachelor’s degree or higher in Computer Scienc...,6+ years software development (minimum 4 years...
15,15,Java Developer,Overview:\r\n\r\nWestern National is seeking a...,Technology/IT,"[Modern Javascript (ES6+), Node, HTML5, CSS3, ...",B.S. Degree in Computer Science or equivalent ...,5+ years of software development experience
16,16,Wordpress Developer,Experience: 2-5 years\r\n\r\nJob Location:- Au...,Technology/IT,"[WordPress, Plugin development, PHP, HTML, HTM...","UG: B.Sc (CS/CSC/IT), BCA, BCS, BE, B.Tech (CS...",2-5 years
17,17,iOS Developer,Job Code : ID190704\r\n\r\nJob Description:\r\...,Technology/IT,"[iOS Development, PhoneGap, Ionic, Titanium, D...","BE (Computers/Information Technology), MCA, BC...",1 to 2 years in iOS Development
18,18,Database Administrator,job description summary highly skilled technic...,Technology/IT,"[Oracle Database (10g, 11g, 12c), Oracle Data ...",Bachelor's degree in Computer Science or Infor...,10+ years of experience in Oracle database adm...
19,20,DevOps Engineer,Job Summary\r\n\r\nOur mission at Style Theory...,Technology/IT,"[AWS, GCP, Linux, Ansible, Chef, Puppet, Terra...",Not specified,At least 3 years of experience in a similar role.
20,21,Database Administrator,country place mortgage founded 1995 subsidiary...,Technology/IT,"[Oracle Database, Linux, SQL, WebLogic, Databa...",Bachelor's degree or comparable industry exper...,2+ years Oracle database experience
21,22,Wordpress Developer,Position: WordPress Developer\r\nLocation: Pra...,Technology/IT,"[WordPress, CSS3, JavaScript, HTML5, jQuery, G...",Bachelor's degree in Computer Science or a sim...,4 to 8 years
22,23,JavaScript Developer,MonetizeMore builds industry leading ad techno...,Technology/IT,"[JavaScript, Python, Flask, PostgreSQL, Linux,...",Not specified,Not specified
23,24,Database Administrator,qualification essential qualification related ...,Technology/IT,"[Database design, Database administration, Tro...",Not specified,Two years of work experience in database desig...
24,25,PHP Developer,Job Summary\r\n**\r\nWe are looking for Freshe...,Technology/IT,"[PHP, HTML5, CSS3, Jquery, WordPress, HTML, CS...",B.E./B.TECH./M.E./M.TECH./MCA,0 - 3 years

==========================================
REQUIRED OUTPUT COLUMNS
==========================================

,Job_Title,Predicted_Category,Required_Skills,Education_Required,Experience_Required
0,Flutter Developer,Technology/IT,[Flutter],Not specified,1 year (Preferred)
1,Django Developer,Technology/IT,"[Python, Django, Flask, REST, RPC, Linux, SQL,...",Not specified,Not specified
2,Machine Learning,Technology/IT,"[Machine Learning, Deep Learning, Python, Java...","Graduate or M.Sc. in Computer Science, Mathema...",At least 3 years of hands-on development of co...
3,iOS Developer,Technology/IT,"[iOS development, Objective-C, Cocoa Touch, Co...",Not specified,Published one or more iOS apps in the App Store
4,Full Stack Developer,Technology/IT,"[React, React Native, Redux, Angular, Vue, Jav...",Not specified,"5+ years web development, 2+ years recent Reac..."
5,Java Developer,Technology/IT,"[C#, .NET, .NET Core, HTML5, CSS3, MsSQL, MySQ...","Bachelor's Degree in Computer Science, Informa...",2 years
6,Full Stack Developer,Technology/IT,"[Node.js, Java, MongoDB, Elasticsearch, Redis,...","B.Sc degree in Computer Science, Engineering, ...",Minimum 2 years of relevant experience
7,JavaScript Developer,Technology/IT,"[ReactJS, NodeJS, Azure Functions, GraphQL, HT...","Any graduation, Any PG, Any Doctorate",3-8 years
8,DevOps Engineer,Technology/IT,"[Bash, Ruby, Python, Java, Puppet, Chef, Cloud...",Not specified,Not specified
9,Software Engineer,Technology/IT,"[REST API, C/C++ (Linux/Unix), Python, Go, Git...","BS or MS in Computer Engineering, Computer Sci...",Minimum 7 years of software development experi...
10,Database Administrator,Technology/IT,"[Advanced SQL, Oracle, Database design, Databa...",Technical bachelor's degree (or higher) in a r...,Typically 9 years of related work experience
11,Machine Learning,Technology/IT,"[TensorFlow, OpenCV, Python, Artificial Neural...",Not specified,2-4 years
12,Machine Learning,Technology/IT,"[Machine Learning, Data Mining, Predictive Mod...","Masters and/or PhD in Computer Science, Machin...",Experience in predictive modelling and analysi...
13,Software Engineer,Technology/IT,"[HTML5, CSS 3.0, Bootstrap, Angular 8+, JavaSc...",Not specified,5-8 years
14,Software Engineer,Technology/IT,"[Object-oriented design, Java, .NET, Relationa...",Bachelor’s degree or higher in Computer Scienc...,6+ years software development (minimum 4 years...
15,Java Developer,Technology/IT,"[Modern Javascript (ES6+), Node, HTML5, CSS3, ...",B.S. Degree in Computer Science or equivalent ...,5+ years of software development experience
16,Wordpress Developer,Technology/IT,"[WordPress, Plugin development, PHP, HTML, HTM...","UG: B.Sc (CS/CSC/IT), BCA, BCS, BE, B.Tech (CS...",2-5 years
17,iOS Developer,Technology/IT,"[iOS Development, PhoneGap, Ionic, Titanium, D...","BE (Computers/Information Technology), MCA, BC...",1 to 2 years in iOS Development
18,Database Administrator,Technology/IT,"[Oracle Database (10g, 11g, 12c), Oracle Data ...",Bachelor's degree in Computer Science or Infor...,10+ years of experience in Oracle database adm...
19,DevOps Engineer,Technology/IT,"[AWS, GCP, Linux, Ansible, Chef, Puppet, Terra...",Not specified,At least 3 years of experience in a similar role.
20,Database Administrator,Technology/IT,"[Oracle Database, Linux, SQL, WebLogic, Databa...",Bachelor's degree or comparable industry exper...,2+ years Oracle database experience
21,Wordpress Developer,Technology/IT,"[WordPress, CSS3, JavaScript, HTML5, jQuery, G...",Bachelor's degree in Computer Science or a sim...,4 to 8 years
22,JavaScript Developer,Technology/IT,"[JavaScript, Python, Flask, PostgreSQL, Linux,...",Not specified,Not specified
23,Database Administrator,Technology/IT,"[Database design, Database administration, Tro...",Not specified,Two years of work experience in database desig...
24,PHP Developer,Technology/IT,"[PHP, HTML5, CSS3, Jquery, WordPress, HTML, CS...",B.E./B.TECH./M.E./M.TECH./MCA,0 - 3 years

#Bonus

In [31]:
import os
import json
import time
import pandas as pd

from dotenv import load_dotenv
from huggingface_hub import InferenceClient

load_dotenv()

HF_TOKEN = os.getenv("HF_TOKEN")

if not HF_TOKEN:
    raise ValueError("HF_TOKEN not found in .env")

MODEL_NAME = "meta-llama/Llama-3.1-8B-Instruct"

client = InferenceClient(
    api_key=HF_TOKEN,
    provider="auto"
)

print("Hugging Face client initialized.")
print("Model:", MODEL_NAME)

Hugging Face client initialized.
Model: meta-llama/Llama-3.1-8B-Instruct

In [33]:
jobs_df = pd.read_csv("job_title_des.csv")

print("Total jobs:", len(jobs_df))
print(jobs_df.columns.tolist())

Total jobs: 2277
['Unnamed: 0', 'Job Title', 'Job Description']

In [34]:
jobs_df = jobs_df.rename(columns={
    "Job Title": "Job_Title",
    "Job Description": "Job_Description"
})

print(jobs_df.columns.tolist())

['Unnamed: 0', 'Job_Title', 'Job_Description']

In [39]:
JOB_PROMPT = """
You are a professional job-posting analysis system.

Analyze the following job posting.

TASK 1:
Classify the job into exactly ONE category:

Technology/IT
Finance
Marketing
Healthcare
Education
Others

TASK 2:
Extract:

1. Required Skills/Technologies
2. Education Requirement
3. Experience Requirement

RULES:
- Only extract information explicitly mentioned in the job posting.
- Do not invent information.
- If education is not mentioned, return "Not specified".
- If experience is not mentioned, return "Not specified".
- Required skills must be a list.
- Return ONLY valid JSON.
- Do not use markdown.
- Do not provide explanations.

Return exactly:

{{
    "Predicted_Category": "Technology/IT",
    "Required_Skills": [],
    "Education_Required": "Not specified",
    "Experience_Required": "Not specified"
}}

JOB TITLE:
{job_title}

JOB DESCRIPTION:
{job_description}
"""

In [40]:
def analyze_job(job_title, job_description):

    prompt = JOB_PROMPT.format(
        job_title=str(job_title),
        job_description=str(job_description)
    )

    response = client.chat.completions.create(
        model=MODEL_NAME,
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0,
        max_tokens=500
    )

    content = response.choices[0].message.content.strip()

    # Remove markdown code fences if the model adds them
    if content.startswith("```"):
        content = content.replace("```json", "")
        content = content.replace("```", "")
        content = content.strip()

    try:
        return json.loads(content)

    except json.JSONDecodeError:
        print("JSON parsing failed:")
        print(content)

        return {
            "Predicted_Category": "Others",
            "Required_Skills": [],
            "Education_Required": "Not specified",
            "Experience_Required": "Not specified"
        }

In [41]:
test_job = jobs_df.iloc[0]

test_result = analyze_job(
    test_job["Job_Title"],
    test_job["Job_Description"]
)

print(json.dumps(test_result, indent=4))

{
    "Predicted_Category": "Technology/IT",
    "Required_Skills": [
        "Flutter"
    ],
    "Education_Required": "Not specified",
    "Experience_Required": "1 year (Preferred)"
}

In [42]:
results = []

CHECKPOINT_EVERY = 25

total_jobs = len(jobs_df)

for index, row in jobs_df.iterrows():

    print(f"Processing {index + 1}/{total_jobs}")

    try:

        result = analyze_job(
            row["Job_Title"],
            row["Job_Description"]
        )

    except Exception as e:

        print(f"ERROR on job {index + 1}: {e}")

        result = {
            "Predicted_Category": "Others",
            "Required_Skills": [],
            "Education_Required": "Not specified",
            "Experience_Required": "Not specified"
        }

    results.append(result)

    # Save checkpoint
    if (index + 1) % CHECKPOINT_EVERY == 0:

        checkpoint_df = jobs_df.iloc[:index + 1].copy()

        checkpoint_df["Predicted_Category"] = [
            r["Predicted_Category"] for r in results
        ]

        checkpoint_df["Required_Skills"] = [
            r["Required_Skills"] for r in results
        ]

        checkpoint_df["Education_Required"] = [
            r["Education_Required"] for r in results
        ]

        checkpoint_df["Experience_Required"] = [
            r["Experience_Required"] for r in results
        ]

        checkpoint_df.to_csv(
            "part2_bonus_checkpoint.csv",
            index=False
        )

        print(
            f"Checkpoint saved: {index + 1}/{total_jobs}"
        )

    # Small delay
    time.sleep(0.3)

Processing 1/2277
Processing 2/2277
Processing 3/2277
Processing 4/2277
Processing 5/2277
Processing 6/2277
Processing 7/2277
Processing 8/2277
Processing 9/2277
Processing 10/2277
Processing 11/2277
Processing 12/2277
Processing 13/2277
Processing 14/2277
Processing 15/2277
ERROR on job 15: 402 Client Error: Payment Required for url: https://router.huggingface.co/novita/v3/openai/chat/completions (Request ID: Root=1-6aa7fd0b-4af5e50c3515817035bfcc77;4531b885-8e11-4b98-8c66-e7051711dfdb)

You have depleted your monthly included credits. Purchase pre-paid credits to continue using Inference Providers. Alternatively, subscribe to PRO to get 20x more included usage.
Processing 16/2277
ERROR on job 16: 402 Client Error: Payment Required for url: https://router.huggingface.co/novita/v3/openai/chat/completions (Request ID: Root=1-6aa7fd0c-3e931772432194ab5afea043;8974c9bc-8388-4886-bb5a-8c9b900f0e95)

You have depleted your monthly included credits. Purchase pre-paid credits to continue using Inference Providers. Alternatively, subscribe to PRO to get 20x more included usage.
Processing 17/2277
ERROR on job 17: 402 Client Error: Payment Required for url: https://router.huggingface.co/novita/v3/openai/chat/completions (Request ID: Root=1-6aa7fd0d-75f4dceb3e123ee317d6391b;3b1891a4-37ac-4473-a2a7-ada71da54027)

You have depleted your monthly included credits. Purchase pre-paid credits to continue using Inference Providers. Alternatively, subscribe to PRO to get 20x more included usage.
Processing 18/2277
ERROR on job 18: 402 Client Error: Payment Required for url: https://router.huggingface.co/novita/v3/openai/chat/completions (Request ID: Root=1-6aa7fd0d-04ad3429409ff15420525d64;c0369bdd-a966-473a-963a-523f2393ef24)

You have depleted your monthly included credits. Purchase pre-paid credits to continue using Inference Providers. Alternatively, subscribe to PRO to get 20x more included usage.
Processing 19/2277
ERROR on job 19: 402 Client Error: Payment Required for url: https://router.huggingface.co/novita/v3/openai/chat/completions (Request ID: Root=1-6aa7fd0e-02d05bed49bd95d6586c85f3;2174fac0-877d-4e52-866e-6a84a204e3d8)

You have depleted your monthly included credits. Purchase pre-paid credits to continue using Inference Providers. Alternatively, subscribe to PRO to get 20x more included usage.
Processing 20/2277
ERROR on job 20: 402 Client Error: Payment Required for url: https://router.huggingface.co/novita/v3/openai/chat/completions (Request ID: Root=1-6aa7fd0e-7f9a50e833907c0a1dc983f8;801869c2-5ab1-45ed-b85c-f27646634ee7)

You have depleted your monthly included credits. Purchase pre-paid credits to continue using Inference Providers. Alternatively, subscribe to PRO to get 20x more included usage.
Processing 21/2277
ERROR on job 21: 402 Client Error: Payment Required for url: https://router.huggingface.co/novita/v3/openai/chat/completions (Request ID: Root=1-6aa7fd0f-30e3a42f069efe2a6db8c8e8;86db742d-6c9a-4d0b-a1e7-fc02ce5b4fbb)

You have depleted your monthly included credits. Purchase pre-paid credits to continue using Inference Providers. Alternatively, subscribe to PRO to get 20x more included usage.
Processing 22/2277
ERROR on job 22: 402 Client Error: Payment Required for url: https://router.huggingface.co/novita/v3/openai/chat/completions (Request ID: Root=1-6aa7fd0f-6ce58caf00ff51285ae7cf3f;0abc1e53-c887-43c6-9ded-d118a6f55b0b)

You have depleted your monthly included credits. Purchase pre-paid credits to continue using Inference Providers. Alternatively, subscribe to PRO to get 20x more included usage.
Processing 23/2277
ERROR on job 23: 402 Client Error: Payment Required for url: https://router.huggingface.co/novita/v3/openai/chat/completions (Request ID: Root=1-6aa7fd10-1d7d7e236cebf683526f1e93;65c4abb8-8d71-4ec3-a8d4-243ed3d16e5d)

You have depleted your monthly included credits. Purchase pre-paid credits to continue using Inference Providers. Alternatively, subscribe to PRO to get 20x more included usage.
Processing 24/2277
ERROR on job 24: 402 Client Error: Payment Required for url: https://router.huggingface.co/novita/v3/openai/chat/completions (Request ID: Root=1-6aa7fd11-3bec438608dd0776363b0797;b43e218a-ae1a-4414-b5fc-dd60f087fe0e)

You have depleted your monthly included credits. Purchase pre-paid credits to continue using Inference Providers. Alternatively, subscribe to PRO to get 20x more included usage.
Processing 25/2277
ERROR on job 25: 402 Client Error: Payment Required for url: https://router.huggingface.co/novita/v3/openai/chat/completions (Request ID: Root=1-6aa7fd11-3f2f16093ee078342b1fa279;d3bbc222-3f58-4c5e-9907-9ea09be0c20c)

You have depleted your monthly included credits. Purchase pre-paid credits to continue using Inference Providers. Alternatively, subscribe to PRO to get 20x more included usage.
Checkpoint saved: 25/2277
Processing 26/2277
ERROR on job 26: 402 Client Error: Payment Required for url: https://router.huggingface.co/novita/v3/openai/chat/completions (Request ID: Root=1-6aa7fd12-51f6008e0ab298422cafaf37;9c78a46e-6bc8-458b-bb12-9133060945d5)

You have depleted your monthly included credits. Purchase pre-paid credits to continue using Inference Providers. Alternatively, subscribe to PRO to get 20x more included usage.
Processing 27/2277
ERROR on job 27: 402 Client Error: Payment Required for url: https://router.huggingface.co/novita/v3/openai/chat/completions (Request ID: Root=1-6aa7fd12-2e43d06b3a751f06287da095;1c9c42a1-1cfd-4abd-9e38-e91a801a7d38)

You have depleted your monthly included credits. Purchase pre-paid credits to continue using Inference Providers. Alternatively, subscribe to PRO to get 20x more included usage.
Processing 28/2277
ERROR on job 28: 402 Client Error: Payment Required for url: https://router.huggingface.co/novita/v3/openai/chat/completions (Request ID: Root=1-6aa7fd13-241bb3675d144f936bab579a;046162d5-b2b0-4702-ad47-f923cb4dd81e)

You have depleted your monthly included credits. Purchase pre-paid credits to continue using Inference Providers. Alternatively, subscribe to PRO to get 20x more included usage.
Processing 29/2277
ERROR on job 29: 402 Client Error: Payment Required for url: https://router.huggingface.co/novita/v3/openai/chat/completions (Request ID: Root=1-6aa7fd14-187bb720065affde2bfd2eb1;356b6561-2688-4850-a1c6-4f742f0a8000)

You have depleted your monthly included credits. Purchase pre-paid credits to continue using Inference Providers. Alternatively, subscribe to PRO to get 20x more included usage.
Processing 30/2277
ERROR on job 30: 402 Client Error: Payment Required for url: https://router.huggingface.co/novita/v3/openai/chat/completions (Request ID: Root=1-6aa7fd14-625c7de144524a7d5f7cd7bc;5df144dd-fd09-4e8e-b4b9-d7a3597cf529)

You have depleted your monthly included credits. Purchase pre-paid credits to continue using Inference Providers. Alternatively, subscribe to PRO to get 20x more included usage.
Processing 31/2277
ERROR on job 31: 402 Client Error: Payment Required for url: https://router.huggingface.co/novita/v3/openai/chat/completions (Request ID: Root=1-6aa7fd15-58478b96283f8c44365c04dc;51c47eca-8e50-43f1-9644-d2da574be4bf)

You have depleted your monthly included credits. Purchase pre-paid credits to continue using Inference Providers. Alternatively, subscribe to PRO to get 20x more included usage.
Processing 32/2277
ERROR on job 32: 402 Client Error: Payment Required for url: https://router.huggingface.co/novita/v3/openai/chat/completions (Request ID: Root=1-6aa7fd15-197414cc74e768fb1b406ce6;c69a5130-1775-4f10-9867-c9675f10b933)

You have depleted your monthly included credits. Purchase pre-paid credits to continue using Inference Providers. Alternatively, subscribe to PRO to get 20x more included usage.
Processing 33/2277
ERROR on job 33: 402 Client Error: Payment Required for url: https://router.huggingface.co/novita/v3/openai/chat/completions (Request ID: Root=1-6aa7fd16-4dcd22ac5d7e4d8857859f27;82a62fb7-3017-4c5e-979b-b24e09011659)

You have depleted your monthly included credits. Purchase pre-paid credits to continue using Inference Providers. Alternatively, subscribe to PRO to get 20x more included usage.
Processing 34/2277
ERROR on job 34: 402 Client Error: Payment Required for url: https://router.huggingface.co/novita/v3/openai/chat/completions (Request ID: Root=1-6aa7fd16-062180fe143d71ee0c4b6603;57157230-11ac-46c2-9fc1-9d941478a041)

You have depleted your monthly included credits. Purchase pre-paid credits to continue using Inference Providers. Alternatively, subscribe to PRO to get 20x more included usage.
Processing 35/2277
ERROR on job 35: 402 Client Error: Payment Required for url: https://router.huggingface.co/novita/v3/openai/chat/completions (Request ID: Root=1-6aa7fd17-0f6f6e263ad777cb3b3bd016;6819f7cb-d276-47f5-b87f-0ee21d93dc5f)

You have depleted your monthly included credits. Purchase pre-paid credits to continue using Inference Providers. Alternatively, subscribe to PRO to get 20x more included usage.
Processing 36/2277
ERROR on job 36: 402 Client Error: Payment Required for url: https://router.huggingface.co/novita/v3/openai/chat/completions (Request ID: Root=1-6aa7fd18-33c564272d0ee23e4c884819;8dae6584-3ad6-4cfb-a690-2b63936ecc0e)

You have depleted your monthly included credits. Purchase pre-paid credits to continue using Inference Providers. Alternatively, subscribe to PRO to get 20x more included usage.
Processing 37/2277
ERROR on job 37: 402 Client Error: Payment Required for url: https://router.huggingface.co/novita/v3/openai/chat/completions (Request ID: Root=1-6aa7fd18-2082af1c388b0d674c99c532;0cd1dd86-19db-44c8-9b68-657c2eb29cbe)

You have depleted your monthly included credits. Purchase pre-paid credits to continue using Inference Providers. Alternatively, subscribe to PRO to get 20x more included usage.
Processing 38/2277
ERROR on job 38: 402 Client Error: Payment Required for url: https://router.huggingface.co/novita/v3/openai/chat/completions (Request ID: Root=1-6aa7fd19-7d66691651f993b633f3c9cd;40ea9a83-79aa-4d9e-bf91-c654bfa532b3)

You have depleted your monthly included credits. Purchase pre-paid credits to continue using Inference Providers. Alternatively, subscribe to PRO to get 20x more included usage.
Processing 39/2277
ERROR on job 39: 402 Client Error: Payment Required for url: https://router.huggingface.co/novita/v3/openai/chat/completions (Request ID: Root=1-6aa7fd19-78e5e683099427104c7efe05;749e0bb5-1142-4fc0-bcfc-a564f255ebfc)

You have depleted your monthly included credits. Purchase pre-paid credits to continue using Inference Providers. Alternatively, subscribe to PRO to get 20x more included usage.
Processing 40/2277
ERROR on job 40: 402 Client Error: Payment Required for url: https://router.huggingface.co/novita/v3/openai/chat/completions (Request ID: Root=1-6aa7fd1a-5cd84b1d41f6ab1f70bbbd43;de0ae74d-dde5-4a4d-bcb7-29787d9b1d3c)

You have depleted your monthly included credits. Purchase pre-paid credits to continue using Inference Providers. Alternatively, subscribe to PRO to get 20x more included usage.
Processing 41/2277
ERROR on job 41: 402 Client Error: Payment Required for url: https://router.huggingface.co/novita/v3/openai/chat/completions (Request ID: Root=1-6aa7fd1a-615fe95c6a7bb6b175d0adfb;2d0d84ba-09f9-4a01-9bdb-c74bafb4809d)

You have depleted your monthly included credits. Purchase pre-paid credits to continue using Inference Providers. Alternatively, subscribe to PRO to get 20x more included usage.
Processing 42/2277
ERROR on job 42: 402 Client Error: Payment Required for url: https://router.huggingface.co/novita/v3/openai/chat/completions (Request ID: Root=1-6aa7fd1b-5b8a81740c5975d17ddb6034;101d6dfa-1d6e-4d64-aa67-7ddccc345044)

You have depleted your monthly included credits. Purchase pre-paid credits to continue using Inference Providers. Alternatively, subscribe to PRO to get 20x more included usage.
Processing 43/2277
ERROR on job 43: 402 Client Error: Payment Required for url: https://router.huggingface.co/novita/v3/openai/chat/completions (Request ID: Root=1-6aa7fd1c-22da214f62d659f8440a94db;d08f692c-ecd3-4c9b-8d05-35115818b070)

You have depleted your monthly included credits. Purchase pre-paid credits to continue using Inference Providers. Alternatively, subscribe to PRO to get 20x more included usage.
Processing 44/2277
ERROR on job 44: 402 Client Error: Payment Required for url: https://router.huggingface.co/novita/v3/openai/chat/completions (Request ID: Root=1-6aa7fd1c-43a5b6656ec25a517ce67d27;1f3443de-19d7-4994-8498-7571eca0752a)

You have depleted your monthly included credits. Purchase pre-paid credits to continue using Inference Providers. Alternatively, subscribe to PRO to get 20x more included usage.
Processing 45/2277
ERROR on job 45: 402 Client Error: Payment Required for url: https://router.huggingface.co/novita/v3/openai/chat/completions (Request ID: Root=1-6aa7fd1d-68e214c07029f5c5492edb37;f0f756c2-ba95-4422-80a4-20f49725f88c)

You have depleted your monthly included credits. Purchase pre-paid credits to continue using Inference Providers. Alternatively, subscribe to PRO to get 20x more included usage.
Processing 46/2277
ERROR on job 46: 402 Client Error: Payment Required for url: https://router.huggingface.co/novita/v3/openai/chat/completions (Request ID: Root=1-6aa7fd1d-45bfe24b6d82b4016e102a3a;338c09c3-df3b-4e73-8d5a-eb1fcd009bf0)

You have depleted your monthly included credits. Purchase pre-paid credits to continue using Inference Providers. Alternatively, subscribe to PRO to get 20x more included usage.
Processing 47/2277
ERROR on job 47: 402 Client Error: Payment Required for url: https://router.huggingface.co/novita/v3/openai/chat/completions (Request ID: Root=1-6aa7fd1e-391208d127183a5b5a42618f;b97b7bf0-59bc-4583-a6d7-a417de1f025b)

You have depleted your monthly included credits. Purchase pre-paid credits to continue using Inference Providers. Alternatively, subscribe to PRO to get 20x more included usage.
Processing 48/2277
ERROR on job 48: 402 Client Error: Payment Required for url: https://router.huggingface.co/novita/v3/openai/chat/completions (Request ID: Root=1-6aa7fd1e-1970ded979eb31bf20288381;0cd58830-81ff-4d75-91e5-1db1ad3bfbae)

You have depleted your monthly included credits. Purchase pre-paid credits to continue using Inference Providers. Alternatively, subscribe to PRO to get 20x more included usage.
Processing 49/2277
ERROR on job 49: 402 Client Error: Payment Required for url: https://router.huggingface.co/novita/v3/openai/chat/completions (Request ID: Root=1-6aa7fd1f-64e8580a238bb83319e82bdf;b566fbcb-9b7e-46bd-84c3-9e7249b21c86)

You have depleted your monthly included credits. Purchase pre-paid credits to continue using Inference Providers. Alternatively, subscribe to PRO to get 20x more included usage.
Processing 50/2277
ERROR on job 50: 402 Client Error: Payment Required for url: https://router.huggingface.co/novita/v3/openai/chat/completions (Request ID: Root=1-6aa7fd1f-1e9367c21ed58c7f161bde07;ef0d4d29-41ce-49ef-a994-6cd3831ac6a1)

You have depleted your monthly included credits. Purchase pre-paid credits to continue using Inference Providers. Alternatively, subscribe to PRO to get 20x more included usage.
Checkpoint saved: 50/2277
Processing 51/2277
ERROR on job 51: 402 Client Error: Payment Required for url: https://router.huggingface.co/novita/v3/openai/chat/completions (Request ID: Root=1-6aa7fd20-381645d33003fb083f252682;664e459a-201d-40ab-88c0-4bb2c92c7d0b)

You have depleted your monthly included credits. Purchase pre-paid credits to continue using Inference Providers. Alternatively, subscribe to PRO to get 20x more included usage.
Processing 52/2277
ERROR on job 52: 402 Client Error: Payment Required for url: https://router.huggingface.co/novita/v3/openai/chat/completions (Request ID: Root=1-6aa7fd20-455cc6360ffded7d58f2ff37;4e11bd86-eb62-4a68-b8aa-9c0f1b1af3a9)

You have depleted your monthly included credits. Purchase pre-paid credits to continue using Inference Providers. Alternatively, subscribe to PRO to get 20x more included usage.
Processing 53/2277
ERROR on job 53: 402 Client Error: Payment Required for url: https://router.huggingface.co/novita/v3/openai/chat/completions (Request ID: Root=1-6aa7fd21-7de5bc95240930372790fa92;a8dfd4a5-17cf-492d-aa0a-8239795183e0)

You have depleted your monthly included credits. Purchase pre-paid credits to continue using Inference Providers. Alternatively, subscribe to PRO to get 20x more included usage.
Processing 54/2277

KeyboardInterrupt:

In [ ]:
jobs_bonus_df = jobs_df.copy()

jobs_bonus_df["Predicted_Category"] = [
    r["Predicted_Category"] for r in results
]

jobs_bonus_df["Required_Skills"] = [
    r["Required_Skills"] for r in results
]

jobs_bonus_df["Education_Required"] = [
    r["Education_Required"] for r in results
]

jobs_bonus_df["Experience_Required"] = [
    r["Experience_Required"] for r in results
]